# Generated by Django 5.1 on 2024-09-27 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoriterestaurant',
            name='added_on',
        ),
        migrations.RemoveField(
            model_name='favoriterestaurant',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='favoriterestaurant',
            name='website_url',
        ),
        migrations.AddField(
            model_name='favoriterestaurant',
            name='rating',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='favoriterestaurant',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='favoriterestaurant',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
