# Generated by Django 5.1.1 on 2024-09-30 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_restaurant_googlereview_userreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='place_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
